### ISSUE TITLE
Feedback - Product Backlog

### ISSUE THREAD

**Issue by jialinw1** [CMPUT301W24T46/QR-CODE-APP#94]
- [x]  Halfway checkpoint should contain more user stories, at least half of the story points. Currently, halfway checkpoints have less than half of the story points.

- [x] US 04.05.01 has no story points associated with it.

- [x] Numbered backlogs.

- [x]  Notes are present for halfway checkpoints.

- [x]  Story points and risk levels are assigned.

**Comment by I3ubble** [comment]
Story label fixed, utilized risk level and used the backlog to track tasks.
