### ISSUE TITLE
Feedback - User Interface Mockups and Storyboard Sequences

### ISSUE THREAD

**Issue by jialinw1** [CMPUT301W24T46/QR-CODE-APP#95]
- [x]  password should not be used for an admin account

- [x]  username and password is not allowed for user and organizers account

- [x] firebase authentication can be used or device-specific log-in could be used.

**Comment by jialinw1** [comment]
Removed the password and username.
Firebase can be used

**Comment by JerryYu-2004** [comment]
Removed user login and signup pages on the storyboard and application. Implemented device specific login for attendees and organizers
